
services:
  mysql:
    image: mysql:8.0
    container_name: ride_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ride_db
    ports:
      - "3307:3306"  #host:container
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
